In [45]:
import pandas as pd

df = pd.read_csv(r"C:\Users\samsu\Downloads\loan.csv")
df.dtypes
df.head(10)
df.describe()

C:\Users\samsu\AppData\Local\Temp\ipykernel_16828\1184111322.py:3: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\samsu\Downloads\loan.csv")

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,3.971700e+04,3.971700e+04,39717.000000,39717.000000,39717.000000,39717.000000,3.971700e+04,39717.000000,39717.000000,39717.000000,...,0.0,0.0,0.0,0.0,39020.000000,39678.0,0.0,0.0,0.0,0.0
mean,6.831319e+05,8.504636e+05,11219.443815,10947.713196,10397.448868,324.561922,6.896893e+04,13.315130,0.146512,0.869200,...,NaN,NaN,NaN,NaN,0.043260,0.0,NaN,NaN,NaN,NaN
std,2.106941e+05,2.656783e+05,7456.670694,7187.238670,7128.450439,208.874874,6.379377e+04,6.678594,0.491812,1.070219,...,NaN,NaN,NaN,NaN,0.204324,0.0,NaN,NaN,NaN,NaN
min,5.473400e+04,7.069900e+04,500.000000,500.000000,0.000000,15.690000,4.000000e+03,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
25%,5.162210e+05,6.667800e+05,5500.000000,5400.000000,5000.000000,167.020000,4.040400e+04,8.170000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
50%,6.656650e+05,8.508120e+05,10000.000000,9600.000000,8975.000000,280.220000,5.900000e+04,13.400000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
75%,8.377550e+05,1.047339e+06,15000.000000,15000.000000,14400.000000,430.780000,8.230000e+04,18.600000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
max,1.077501e+06,1.314167e+06,35000.000000,35000.000000,35000.000000,1305.190000,6.000000e+06,29.990000,11.000000,8.000000,...,NaN,NaN,NaN,NaN,2.000000,0.0,NaN,NaN,NaN,NaN

In [46]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending = False)
missing

bc_open_to_buy                39717
acc_open_past_24mths          39717
bc_util                       39717
mo_sin_old_il_acct            39717
mo_sin_old_rev_tl_op          39717
                              ...
collections_12_mths_ex_med       56
revol_util                       50
tax_liens                        39
title                            11
last_credit_pull_d                2
Length: 68, dtype: int64

In [47]:
cols_to_drop = df.columns[df.isnull().sum() == len(df)].tolist()
df = df.drop(columns = cols_to_drop)
print(f"dropped columns {len(cols_to_drop)} in list")
print(df.shape)

dropped columns 54 in list
(39717, 57)

In [48]:
df = df.drop(columns = ["policy_code", "next_pymnt_d", "url", "desc", "zip_code", "collection_recovery_fee"])
df.shape

(39717, 51)

In [ ]:
df.to_csv(r"D:\CV\lending_club_cleaned.csv", index=False)

In [ ]:
df["revol_util"] = df["revol_util"].str.replace("%", "").astype(float)

In [ ]:
# replaceing droping values for nulls 

df = df.dropna(subset=["last_credit_pull_d"])
df["title"] = df["title"].fillna("Not Provided")
df["tax_liens"] = df["tax_liens"].fillna(0)
df["revol_util"] = df["revol_util"].fillna(df["revol_util"].median())
df["chargeoff_within_12_mths"] = df["chargeoff_within_12_mths"].fillna(df["chargeoff_within_12_mths"].median())
df["collections_12_mths_ex_med"] = df["collections_12_mths_ex_med"].fillna(df["collections_12_mths_ex_med"].median())
df["last_pymnt_d"] = df["last_pymnt_d"].fillna(df["last_pymnt_d"].mode()[0])
df["pub_rec_bankruptcies"] = df["pub_rec_bankruptcies"].fillna(df["pub_rec_bankruptcies"].median())
df["emp_length"] = df["emp_length"].fillna(df["emp_length"].mode()[0])
df["emp_title"] = df["emp_title"].fillna("Not Provided")
df = df.drop(columns=["mths_since_last_record", "mths_since_last_delinq"])

In [ ]:
# Data Validation 

print(df["revol_util"].dtype)
print(df["int_rate"].dtype)

In [ ]:
df["int_rate"] = df["int_rate"].str.replace("%","").astype("float")
print(df["int_rate"].dtype)

In [ ]:
print(df.isnull().sum().sum())

In [ ]:
df.to_csv(r"D:\CV\lending_club_cleaned_2.csv", index=False)

In [ ]:
import pandas as pd 
df = pd.read_csv(r"D:\CV\lending_club_cleaned_2.csv")
df.shape

In [ ]:
# Check average interest rate by grade — should increase from A to G
df.groupby("grade")["int_rate"].mean().sort_index()

In [ ]:
invalid_loan_amnt = df[df["loan_amnt"] <= 0]
print(f"{len(invalid_loan_amnt)} invaild_loan_amnt")

invalid_dti = df[df["dti"] <= 0]
print(f"{len(invalid_dti)} invalid_dti worth investigating")

invalid_funded_amt = df[df["funded_amnt"] > df["loan_amnt"]]
print(f"{len(invalid_funded_amt)} invalid_funded_amt")

invalid_int_rate = df[(df["int_rate"] < 0) | (df["int_rate"] > 100)]
print(f"{len(invalid_int_rate)} invalid_int_rate")

In [ ]:
print(df[df["dti"] <= 0]["dti"].describe())

In [ ]:
df.groupby("grade")["int_rate"].mean()

In [ ]:
df.to_csv(r"D:\Phase 2 Progress\Data Analytics\lending_club_validated.csv", index=False)

In [ ]:
print(df["loan_status"].value_counts())

In [10]:
import pandas as pd
df = pd.read_csv(r"D:\Phase 2 Progress\Data Analytics\lending_club_validated.csv")
df.head(6)
df.tail(10)
df.describe()
df.info()
df.shape

df["loan_status"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39715 entries, 0 to 39714
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          39715 non-null  int64
 1   member_id                   39715 non-null  int64
 2   loan_amnt                   39715 non-null  int64
 3   funded_amnt                 39715 non-null  int64
 4   funded_amnt_inv             39715 non-null  float64
 5   term                        39715 non-null  object
 6   int_rate                    39715 non-null  float64
 7   installment                 39715 non-null  float64
 8   grade                       39715 non-null  object
 9   sub_grade                   39715 non-null  object
 10  emp_title                   39715 non-null  object
 11  emp_length                  39715 non-null  object
 12  home_ownership              39715 non-null  object
 13  annual_inc                  39715 non-null  float64
 14  verification_status         39715 non-null  object
 15  issue_d                     39715 non-null  object
 16  loan_status                 39715 non-null  object
 17  pymnt_plan                  39715 non-null  object
 18  purpose                     39715 non-null  object
 19  title                       39715 non-null  object
 20  addr_state                  39715 non-null  object
 21  dti                         39715 non-null  float64
 22  delinq_2yrs                 39715 non-null  int64
 23  earliest_cr_line            39715 non-null  object
 24  inq_last_6mths              39715 non-null  int64
 25  open_acc                    39715 non-null  int64
 26  pub_rec                     39715 non-null  int64
 27  revol_bal                   39715 non-null  int64
 28  revol_util                  39715 non-null  float64
 29  total_acc                   39715 non-null  int64
 30  initial_list_status         39715 non-null  object
 31  out_prncp                   39715 non-null  float64
 32  out_prncp_inv               39715 non-null  float64
 33  total_pymnt                 39715 non-null  float64
 34  total_pymnt_inv             39715 non-null  float64
 35  total_rec_prncp             39715 non-null  float64
 36  total_rec_int               39715 non-null  float64
 37  total_rec_late_fee          39715 non-null  float64
 38  recoveries                  39715 non-null  float64
 39  last_pymnt_d                39715 non-null  object
 40  last_pymnt_amnt             39715 non-null  float64
 41  last_credit_pull_d          39715 non-null  object
 42  collections_12_mths_ex_med  39715 non-null  float64
 43  application_type            39715 non-null  object
 44  acc_now_delinq              39715 non-null  int64
 45  chargeoff_within_12_mths    39715 non-null  float64
 46  delinq_amnt                 39715 non-null  int64
 47  pub_rec_bankruptcies        39715 non-null  float64
 48  tax_liens                   39715 non-null  float64
dtypes: float64(19), int64(12), object(18)
memory usage: 14.8+ MB

loan_status
Fully Paid     32949
Charged Off     5626
Current         1140
Name: count, dtype: int64

In [12]:
# Filter the outcome data

df_default = df[df["loan_status"].isin(["Fully Paid","Charged Off"])]
df_default["loan_status"].value_counts()

loan_status
Fully Paid     32949
Charged Off     5626
Name: count, dtype: int64

In [18]:
# default rate

default_rate = (df_default["loan_status"] == "Charged Off").mean() * 100

default_rate

14.584575502268308

In [19]:
# Default rate by loan grade

df_default.groupby("grade")["loan_status"].value_counts()

grade  loan_status
A      Fully Paid      9442
       Charged Off      602
B      Fully Paid     10250
       Charged Off     1424
C      Fully Paid      6487
       Charged Off     1347
D      Fully Paid      3967
       Charged Off     1118
E      Fully Paid      1948
       Charged Off      715
F      Fully Paid       657
       Charged Off      319
G      Fully Paid       198
       Charged Off      101
Name: count, dtype: int64

In [21]:
# Calculate default rate by grade

grade_default_rate = df_default.groupby("grade")["loan_status"].apply( lambda x: (x == "Charged Off").mean() * 100 )

grade_default_rate.round(2)

grade
A     5.99
B    12.20
C    17.19
D    21.99
E    26.85
F    32.68
G    33.78
Name: loan_status, dtype: float64

In [30]:
# Checking Homeownership 

df_default["home_ownership"].value_counts()

df_default.groupby("home_ownership")["loan_status"].value_counts()

df_default.groupby("home_ownership")["loan_status"].apply(lambda x : (x == "Charged Off").mean() * 100).round(2)

home_ownership
MORTGAGE    13.67
NONE         0.00
OTHER       18.37
OWN         14.89
RENT        15.36
Name: loan_status, dtype: float64

In [60]:
df_default["purpose"].value_counts()

df_default.groupby("purpose")["loan_status"].apply( lambda x: (x == "Charged Off").mean() * 100).round(2).sort_values(ascending = False)

df_default.groupby("purpose")["loan_status"].value_counts()

df_default.groupby("purpose")["int_rate"].mean().round(2).sort_values(ascending=False)

purpose
small_business        12.90
debt_consolidation    12.40
house                 12.16
wedding               11.78
other                 11.72
educational           11.65
credit_card           11.62
moving                11.53
renewable_energy      11.44
medical               11.43
home_improvement      11.29
vacation              10.83
major_purchase        10.80
car                   10.46
Name: int_rate, dtype: float64

In [61]:
df_default.groupby("loan_status")["annual_inc"].agg(["count", "mean", "median"]).round(2)

             count      mean   median
loan_status
Charged Off   5626  62421.33  53000.0
Fully Paid   32949  69860.98  60000.0

In [63]:
df_default.groupby("verification_status")["loan_status"].value_counts()

df_default.groupby("verification_status")["loan_status"].apply(
    lambda x: (x == "Charged Off").mean() * 100
).round(2).sort_values(ascending=False)

verification_status
Verified           16.80
Source Verified    14.82
Not Verified       12.83
Name: loan_status, dtype: float64

In [64]:
df_default.groupby(
    ["grade", "verification_status"]
)["loan_status"].apply(
    lambda x: (x == "Charged Off").mean() * 100
).round(2)

grade  verification_status
A      Not Verified            6.11
       Source Verified         5.52
       Verified                6.24
B      Not Verified           11.59
       Source Verified        12.34
       Verified               13.01
C      Not Verified           17.08
       Source Verified        16.49
       Verified               17.90
D      Not Verified           21.35
       Source Verified        23.72
       Verified               21.42
E      Not Verified           23.56
       Source Verified        27.40
       Verified               28.16
F      Not Verified           27.11
       Source Verified        34.19
       Verified               33.64
G      Not Verified           39.53
       Source Verified        38.81
       Verified               30.69
Name: loan_status, dtype: float64

In [31]:
df_default["dti"].describe()

count    38575.000000
mean        13.273294
std          6.672742
min          0.000000
25%          8.130000
50%         13.370000
75%         18.560000
max         29.990000
Name: dti, dtype: float64

In [33]:
df_default["dti_group"] = pd.qcut(df_default["dti"], q = 4, labels = ["Low","Low to Mid","Mid to High","Above High"])
df_default["dti_group"].value_counts()

C:\Users\samsu\AppData\Local\Temp\ipykernel_29712\18410294.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_default["dti_group"] = pd.qcut(df_default["dti"], q = 4, labels = ["Low","Low to Mid","Mid to High","Above High"])

dti_group
Mid to High    9650
Low            9649
Low to Mid     9649
Above High     9627
Name: count, dtype: int64

In [36]:
dti_default_rate = df_default.groupby("dti_group")["loan_status"].apply(lambda x: (x == "Charged Off").mean() * 100)
dti_default_rate.round(2)

C:\Users\samsu\AppData\Local\Temp\ipykernel_29712\2976461719.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dti_default_rate = df_default.groupby("dti_group")["loan_status"].apply(lambda x: (x == "Charged Off").mean() * 100)

dti_group
Low            12.34
Low to Mid     13.83
Mid to High    15.39
Above High     16.79
Name: loan_status, dtype: float64

In [37]:
df_default["loan_amnt"].describe()

count    38575.000000
mean     11047.442644
std       7348.389581
min        500.000000
25%       5300.000000
50%       9600.000000
75%      15000.000000
max      35000.000000
Name: loan_amnt, dtype: float64

In [38]:
df_default.groupby("loan_status")["loan_amnt"].agg(["count", "mean", "sum"])

             count          mean        sum
loan_status
Charged Off   5626  12105.647885   68106375
Fully Paid   32949  10866.755440  358048725

In [39]:
df_default["loan_amnt_group"] = pd.qcut(
    df_default["loan_amnt"],
    q=4,
    labels=["Low", "Low to Mid", "Mid to High", "High"]
)

df_default["loan_amnt_group"].value_counts()

C:\Users\samsu\AppData\Local\Temp\ipykernel_29712\2086715892.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_default["loan_amnt_group"] = pd.qcut(

loan_amnt_group
Mid to High    10645
Low             9662
Low to Mid      9648
High            8620
Name: count, dtype: int64

In [40]:
loan_amnt_default_rate = df_default.groupby("loan_amnt_group")["loan_status"].apply(
    lambda x: (x == "Charged Off").mean() * 100
)

loan_amnt_default_rate.round(2)

C:\Users\samsu\AppData\Local\Temp\ipykernel_29712\1801509240.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  loan_amnt_default_rate = df_default.groupby("loan_amnt_group")["loan_status"].apply(

loan_amnt_group
Low            13.88
Low to Mid     12.69
Mid to High    13.57
High           18.75
Name: loan_status, dtype: float64

In [41]:
df_default["int_rate"].describe()

count    38575.000000
mean        11.932364
std          3.691339
min          5.420000
25%          8.940000
50%         11.710000
75%         14.380000
max         24.400000
Name: int_rate, dtype: float64

In [42]:
df_default.groupby("grade")["int_rate"].mean().round(2)

grade
A     7.33
B    11.01
C    13.53
D    15.66
E    17.63
F    19.64
G    21.31
Name: int_rate, dtype: float64

In [43]:
df_default.groupby(["grade", "verification_status"])["int_rate"].mean().round(2)

grade  verification_status
A      Not Verified            7.39
       Source Verified         7.19
       Verified                7.35
B      Not Verified           10.97
       Source Verified        10.96
       Verified               11.11
C      Not Verified           13.34
       Source Verified        13.71
       Verified               13.67
D      Not Verified           15.25
       Source Verified        15.93
       Verified               15.89
E      Not Verified           17.01
       Source Verified        17.71
       Verified               17.89
F      Not Verified           18.72
       Source Verified        19.84
       Verified               19.83
G      Not Verified           20.77
       Source Verified        21.57
       Verified               21.35
Name: int_rate, dtype: float64

In [44]:
df_default.groupby("home_ownership")["int_rate"].mean().round(2)

home_ownership
MORTGAGE    11.66
NONE         8.70
OTHER       12.04
OWN         11.69
RENT        12.22
Name: int_rate, dtype: float64

In [46]:
df_default.groupby("dti_group")["int_rate"].mean().round(2)

C:\Users\samsu\AppData\Local\Temp\ipykernel_29712\1779378474.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_default.groupby("dti_group")["int_rate"].mean().round(2)

dti_group
Low            11.24
Low to Mid     11.83
Mid to High    12.29
Above High     12.37
Name: int_rate, dtype: float64

In [47]:
df_default.groupby(
    pd.qcut(df_default["annual_inc"], q=4),
    observed=True
)["int_rate"].mean().round(2)

annual_inc
(3999.999, 40000.0]     11.67
(40000.0, 58852.56]     11.81
(58852.56, 82000.0]     11.95
(82000.0, 6000000.0]    12.30
Name: int_rate, dtype: float64

In [48]:
grade_dti_default = df_default.groupby(
    ["grade", "dti_group"],
    observed=True
)["loan_status"].apply(
    lambda x: (x == "Charged Off").mean() * 100
)

grade_dti_default.round(2)

grade  dti_group
A      Low             4.68
       Low to Mid      5.73
       Mid to High     6.79
       Above High      7.65
B      Low            11.72
       Low to Mid     10.89
       Mid to High    12.50
       Above High     13.64
C      Low            15.46
       Low to Mid     15.73
       Mid to High    17.53
       Above High     19.58
D      Low            20.95
       Low to Mid     23.90
       Mid to High    20.35
       Above High     22.70
E      Low            24.73
       Low to Mid     27.33
       Mid to High    28.16
       Above High     26.71
F      Low            34.83
       Low to Mid     32.91
       Mid to High    31.42
       Above High     32.46
G      Low            40.91
       Low to Mid     26.15
       Mid to High    31.17
       Above High     36.26
Name: loan_status, dtype: float64

In [49]:
grade_loan_default = df_default.groupby(
    ["grade", "loan_amnt_group"],
    observed=True
)["loan_status"].apply(
    lambda x: (x == "Charged Off").mean() * 100
)

grade_loan_default.round(2)

grade  loan_amnt_group
A      Low                 7.26
       Low to Mid          5.82
       Mid to High         5.35
       High                4.26
B      Low                12.69
       Low to Mid         12.01
       Mid to High        11.70
       High               12.48
C      Low                17.60
       Low to Mid         15.97
       Mid to High        16.52
       High               18.86
D      Low                23.08
       Low to Mid         21.24
       Mid to High        20.63
       High               23.21
E      Low                27.67
       Low to Mid         25.06
       Mid to High        25.81
       High               27.77
F      Low                25.00
       Low to Mid         33.01
       Mid to High        27.31
       High               36.02
G      Low                50.00
       Low to Mid         38.10
       Mid to High        43.64
       High               29.27
Name: loan_status, dtype: float64

In [50]:
grade_dti_rate = df_default.groupby(
    ["grade", "dti_group"],
    observed=True
)["int_rate"].mean()

grade_dti_rate.round(2)

grade  dti_group
A      Low             7.28
       Low to Mid      7.34
       Mid to High     7.39
       Above High      7.34
B      Low            10.94
       Low to Mid     11.01
       Mid to High    11.03
       Above High     11.05
C      Low            13.47
       Low to Mid     13.52
       Mid to High    13.52
       Above High     13.61
D      Low            15.57
       Low to Mid     15.72
       Mid to High    15.64
       Above High     15.71
E      Low            17.53
       Low to Mid     17.67
       Mid to High    17.66
       Above High     17.64
F      Low            19.59
       Low to Mid     19.65
       Mid to High    19.61
       Above High     19.71
G      Low            21.16
       Low to Mid     21.27
       Mid to High    21.65
       Above High     21.17
Name: int_rate, dtype: float64

In [51]:
grade_loan_rate = df_default.groupby(
    ["grade", "loan_amnt_group"],
    observed=True
)["int_rate"].mean()

grade_loan_rate.round(2)

grade  loan_amnt_group
A      Low                 7.25
       Low to Mid          7.34
       Mid to High         7.37
       High                7.45
B      Low                10.95
       Low to Mid         10.94
       Mid to High        11.00
       High               11.16
C      Low                13.53
       Low to Mid         13.42
       Mid to High        13.54
       High               13.65
D      Low                15.51
       Low to Mid         15.43
       Mid to High        15.71
       High               15.91
E      Low                17.25
       Low to Mid         17.28
       Mid to High        17.57
       High               17.89
F      Low                19.19
       Low to Mid         19.29
       Mid to High        19.38
       High               19.89
G      Low                20.92
       Low to Mid         20.84
       Mid to High        21.26
       High               21.41
Name: int_rate, dtype: float64

In [52]:
grade_exposure = df_default.groupby("grade")["loan_amnt"].agg(
    ["count", "sum", "mean"]
)

grade_exposure.round(2)

       count        sum      mean
grade
A      10044   86574425   8619.52
B      11674  127658600  10935.29
C       7834   84728775  10815.52
D       5085   61720550  12137.77
E       2663   41756150  15680.12
F        976   17660950  18095.24
G        299    6055650  20253.01

In [53]:
grade_default_exposure = df_default[
    df_default["loan_status"] == "Charged Off"
].groupby("grade")["loan_amnt"].agg(
    ["count", "sum", "mean"]
)

grade_default_exposure.round(2)

       count       sum      mean
grade
A        602   4695550   7799.92
B       1424  15535725  10909.92
C       1347  14876900  11044.47
D       1118  13644800  12204.65
E        715  11332625  15849.83
F        319   6147950  19272.57
G        101   1872825  18542.82

In [54]:
total_exposure = df_default["loan_amnt"].sum()

charged_off_exposure = df_default[
    df_default["loan_status"] == "Charged Off"
]["loan_amnt"].sum()

(charged_off_exposure / total_exposure * 100).round(2)

15.98